name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        haxe-version:
          - stable
          - nightly
        target:
          - interp
          - node
          - neko
          - python
          - php
          - cpp
          - js
          - jvm

    steps:
      - uses: actions/checkout@v6

      - name: Cache Haxe
        uses: actions/cache@v6
        with:
          path: ~/haxe
          key: haxe

      - uses: lix-pm/setup-lix@master
      - run: lix install haxe ${{ matrix.haxe-version }}
      - run: lix download
      - run: lix run travix ${{ matrix.target }}
